apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: cluster-k3d-first
servers: 1
agents: 3
image: rancher/k3s:v1.25.15-rc1-k3s1
kubeAPI:
  hostPort: "6443" 
volumes: # repeatable flags are represented as YAML lists
  - volume: "$PWD/Volume:/tmp/k3dvol:shared" # same as `--volume '/my/host/path:/path/in/node@server:0;agent:*'`
    nodeFilters:
      - server:*
      - agent:*
  - volume: "$PWD/Manifest/calico/tigera-operator.yaml:/var/lib/rancher/k3s/server/manifests/tigera-operator.yaml" # same as `--volume '/my/host/path:/path/in/node@server:0;agent:*'`
    nodeFilters:
      - server:*
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*
      - arg: "--disable=servicelb"
        nodeFilters:
          - server:*
      - arg: "--disable=metrics-server"
        nodeFilters:
          - server:*
      - arg: "--disable=network-policy"
        nodeFilters:
          - server:*
      - arg: "--flannel-backend=none"
        nodeFilters:
          - server:*
      - arg: "--cluster-cidr=192.168.0.0/16"
        nodeFilters:
          - server:*
      - arg: "--service-cidr=192.168.128.0/16"
        nodeFilters:
          - server:*